// This file is auto-generated by the Markup Converter.

namespace TimPurdum.Dev;

public record LinkData(string Title, string SubTitle, string Url, DateTime PublishedDate, string Author);

public static class NavigationLinks
{
    public static readonly List<LinkData> Posts = 
    [        new LinkData("Creating a static website with Jekyll", "", "/post/2022/11/7/static-site-with-jekyll",
           new DateTime(2022, 11, 7),
           ""),
        new LinkData("Adding a Mastodon Feed to your Blog", "", "/post/2022/11/19/mastodon-feed-in-jekyll",
           new DateTime(2022, 11, 19),
           ""),
        new LinkData("Let the Sunshine In", "Finding Your Daylight with GeoBlazor", "/post/2022/12/10/let-the-sunshine-in-blazor",
           new DateTime(2022, 12, 10),
           ""),
        new LinkData("Creating GeoBlazor", "How I started an open source library", "/post/2023/4/22/creating-geoblazor",
           new DateTime(2023, 4, 22),
           ""),
        new LinkData("LINQ Equivalents in JavaScript", "Move Seamlessly Between Languages", "/post/2023/7/22/linq-and-javascript",
           new DateTime(2023, 7, 22),
           ""),
        new LinkData("Using ESBuild with Blazor", "How to Bundle JavaScript packages and Compile TypeScript for your Blazor project", "/post/2023/10/8/using-esbuild-with-blazor",
           new DateTime(2023, 10, 8),
           ""),
        new LinkData("Comparing Blazor Project Structure in .NET 7 and 8", "Understanding How to Set Up or Update a Complex Project", "/post/2023/10/14/comparing-blazor-net-7-8",
           new DateTime(2023, 10, 14),
           ""),
        new LinkData("VS Live Chicago Presentation Links", "", "/post/2024/5/1/vslive-chicago",
           new DateTime(2024, 5, 1),
           ""),
        new LinkData("TechBash 2024 Presentation Links", "", "/post/2024/9/25/tech-bash",
           new DateTime(2024, 9, 25),
           ""),
        new LinkData("Iowa Code Camp 2024 Presentation Links", "", "/post/2024/10/26/iowa-code-camp",
           new DateTime(2024, 10, 26),
           ""),
        new LinkData("Geographically Visualizing Customer Data with Blazor and ArcGIS", "", "/post/2025/4/26/geographically-visualizing-customer-data",
           new DateTime(2025, 4, 26),
           ""),
        new LinkData("Blazor vs. Next.js: Getting Started with Interactive Web Applications", "", "/post/2025/5/11/comparing-blazor-and-react",
           new DateTime(2025, 5, 11),
           ""),
    ];
    
    public static readonly List<LinkData> Pages = [];
}
