# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tim Purdum
email: tim.purdum@dymaptic.com
description: >- # this means to ignore newlines until "baseurl:"
  Tim Purdum is the visionary behind the <a target="_blank" href="https://www.geoblazor.com"><img src="/assets/geoblazor.png">GeoBlazor</a> mapping library and serves as the Director of Product Development at <a target="_blank" href="https://www.dymaptic.com"><img src="https://www.dymaptic.com/wp-content/uploads/2021/02/dymaptic-smaller.png" alt="dymaptic logo" />dymaptic</a>.
  With a robust background in .NET and web technologies, Tim has been focused on Geographic Information Systems (GIS) since 2021. His expertise and passion for technology have made him a sought-after speaker at numerous conferences, including <a target="_blank" href="https://vslive.com/home.aspx">Visual Studio Live</a>, <a target="_blank" href="https://techbash.com/">TechBash</a>, <a target="_blank" href="https://iowacodecamp.com/">Iowa Code Camp</a>, and <a target="_blank" href="https://www.devupconf.org/">DevUp</a>. Tim lives in Cedar Falls, Iowa.
baseurl: /
url: https://timpurdum.github.io
github_username:  TimPurdum
mastodon:
  - username: TimPurdum
    instance: dotnet.social
bsky_username: timpurdum.dev
linkedin_username: crttim

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
